from tkinter import *
root= Tk()
a1= StringVar()
f = Frame(root)
f.pack()
f1= Frame(f, height=600, width=600,bg="lightblue")
f1.pack()
img= PhotoImage(file= "bananas.png")
l1= Label(f1,image=img)
l1.pack()
l2= Label(f1,text= "colours!", bg="black",fg= "white",justify= "center")
l2.pack()
b= Button(f1, text= "click me!")
b.pack()
def print_hello():
    print("hello")
b1= Button(f1, text="Submit", command= print_hello, fg="black", state="normal")
b1.pack()
release= StringVar()
ra= Radiobutton(f1, text= "Option A", variable=release, value=0)
rb= Radiobutton(f1, text= "Option B", variable= release, value= 1)
rp= Radiobutton(f1, text= "Option C", variable= release, value= 2)
ra.pack()
rb.pack()
rp.pack()
textbox= StringVar()
entrybox= Entry(f1,textvariable= textbox)
entrybox.pack()
def print_sanjamiscool():
    print("sanjam is cool.")
b= Button(f1,text= "sanjam button", command= print_sanjamiscool,fg= "black", state= "normal")
b.pack()
b["bg"]= "red"
l2= Label(f1, text= "colours!", bg= "black", justify= "center")
val= l2.cget("justify")
print(val)
val= b1.cget("state")
l2.configure(text= "sanjamiscool", bg="red")
root.mainloop()